# This is a basic workflow to help you get started with Actions

name: Aprendiendo GitHub Actions
run-name: Estoy aprendiendo Github Actions!

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "hola-mundo"
  hola-mundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checout
        uses: actions/checkout@v4

      - name: PHP Runner
        uses: franzliedke/gh-action-php@0.2.0

      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Correr script
        run: php index.php